import Foundation

func L(_ key: String, _ arg: String = "") -> String {
    let isGreek = Locale.preferredLanguages.first?.hasPrefix("el") ?? true
    
    let strings: [String: (el: String, en: String)] = [
        "about_menu": ("Σχετικά με το HelloMac", "About HelloMac"),
        "about_text": ("Έκδοση: 3.0.1\n\nKonstantinos2106\n\nΠραγματοποιήστε κλήσεις απευθείας από το Mac σας\n\nΣυντόμευση: Ctrl + Option + Cmd + H", "Version: 3.0.1\n\nKonstantinos2106\n\nMake calls directly from your Mac via your iPhone\n\nShortcut: Ctrl + Option + Cmd + H"),
        "learn_more": ("Δείτε περισσότερα", "Learn More"),
        "check_updates": ("Έλεγχος για Ενημερώσεις...", "Check for Updates..."),
        "exit": ("Τερματισμός HelloMac", "Quit HelloMac"),
        "tools": ("Εργαλεία", "Tools"),
        "contacts": ("Επαφές", "Contacts"),
        "keypad": ("Πλήκτρα", "Keypad"),
        "dialer_title": ("Πλήκτρα", "Keypad"),
        "favorites": ("Αγαπημένα", "Favorites"),
        "history": ("Ιστορικό", "History"),
        "add_contact_menu": ("Προσθήκη Επαφής", "Add Contact"),
        "add_number_to_new_contact": ("Προσθήκη σε νέα επαφή", "Add to new contact"),
        "remove_contact_menu": ("Διαγραφή Επαφής", "Remove Contact"),
        "show_favorites_menu": ("Αγαπημένα", "Favorites"),
        "add_tooltip": ("Προσθήκη", "Add"),
        "remove_tooltip": ("Διαγραφή", "Delete"),
        "clear_history": ("Καθαρισμός", "Clear"),
        "no_contacts": ("Δεν υπάρχουν επαφές.\nΕπιλέξτε «+» για προσθήκη.", "No contacts.\nSelect “+” to add one."),
        "no_group_filter_results_single": ("Δεν βρέθηκαν αποτελέσματα στην ομάδα «%@».", "No results found in the “%@” group."),
        "no_group_filter_results_multiple": ("Δεν βρέθηκαν αποτελέσματα στις επιλεγμένες ομάδες.", "No results found in the selected groups."),
        "groups_manage_menu_item": ("Διαχείριση ομάδων...", "Manage groups..."),
        "no_favorites": ("Δεν υπάρχουν αγαπημένες επαφές.\nΕπιλέξτε τις 3 τελίτσες σε μια επαφή για προσθήκη.", "No favorite contacts.\nSelect the 3 dots on a contact to add one."),
        "no_history": ("Δεν υπάρχει ιστορικό κλήσεων.", "No call history."),
        "call_tooltip": ("Κλήση", "Call"),
        "favorite_add_tooltip": ("Προσθήκη στα Αγαπημένα", "Add to Favorites"),
        "favorite_remove_tooltip": ("Αφαίρεση από τα Αγαπημένα", "Remove from Favorites"),
        "new_contact": ("Νέα Επαφή", "New Contact"),
        "name": ("Όνομα", "Name"),
        "last_name": ("Επώνυμο", "Last Name"),
        "phone": ("Τηλέφωνο", "Phone"),
        "first_name_placeholder": ("Όνομα", "First name"),
        "last_name_placeholder": ("Επώνυμο", "Last name"),
        "phone_placeholder": ("Τηλέφωνο", "Phone"),
        "add_btn": ("Προσθήκη", "Add"),
        "cancel_btn": ("Άκυρο", "Cancel"),
        "fill_fields": ("Απαιτούνται τουλάχιστον όνομα και τηλέφωνο", "First name and phone number are required"),
        "select_to_delete": ("Επιλέξτε επαφή για διαγραφή", "Select a contact to delete"),
        "delete_btn": ("Διαγραφή", "Delete"),
        "close_btn": ("Κλείσιμο", "Close"),
        "select_one_to_delete": ("Επιλέξτε μια επαφή για διαγραφή", "Please select a contact to delete"),
        "delete_alert_title": ("Διαγραφή επαφής", "Delete contact"),
        "delete_alert_text": ("Η επαφή \"%@\" θα διαγραφεί οριστικά.", "The contact \"%@\" will be permanently deleted."),
        "clear_history_alert_title": ("Καθαρισμός ιστορικού", "Clear history"),
        "clear_history_alert_text": ("Το ιστορικό κλήσεων θα διαγραφεί οριστικά.", "All call history will be permanently deleted."),
        "ok": ("OK", "OK"),

        // --- ΥΠΕΝΘΥΜΙΣΕΙΣ (ΕΝΟΠΟΙΗΜΕΝΗ ΟΡΟΛΟΓΙΑ) ---
        "set_reminder_tooltip": ("Ορισμός Υπενθύμισης", "Set Reminder"),
        "tab_reminders": ("Υπενθυμίσεις", "Reminders"),
        "enable_call_reminders_tab": ("Ενεργοποίηση υπενθυμίσεων", "Enable call reminders"),
        "keep_reminder_history_tab": ("Διατήρηση ιστορικού υπενθυμίσεων", "Keep reminder history"),
        "show_detail_reminder_btn": ("Εμφάνιση πλήκτρου στις λεπτομέρειες επαφής", "Show button in contact details"),
        "show_general_reminder_btn": ("Εμφάνιση πλήκτρου στη λίστα Επαφών", "Show button in Contacts list"),
        "reminder_notification_title": ("Υπενθύμιση Κλήσης: %@", "Call Reminder: %@"),
        "reminder_notification_default_body": ("Μην ξεχάσετε να πραγματοποιήσετε αυτήν την κλήση.", "Don't forget to make this call."),
        "reminder_setup_title": ("Υπενθύμιση για: %@", "Reminder for: %@"),
        "reminder_message_label": ("Μήνυμα (προαιρετικό):", "Message (optional):"),
        "reminder_date_label": ("Ημερομηνία & Ώρα:", "Date & Time:"),
        "reminder_first_label": ("1η Υπενθύμιση:", "1st Reminder:"),
        "reminder_second_label": ("2η Υπενθύμιση:", "2nd Reminder:"),
        "reminder_at_time": ("Κατά την ώρα του συμβάντος", "At time of event"),
        "reminder_5_min": ("5 λεπτά πριν", "5 minutes before"),
        "reminder_10_min": ("10 λεπτά πριν", "10 minutes before"),
        "reminder_30_min": ("30 λεπτά πριν", "30 minutes before"),
        "reminder_1_hour": ("1 ώρα πριν", "1 hour before"),
        "reminder_none": ("Καμία", "None"),
        "reminder_custom": ("Προσαρμοσμένη...", "Custom..."),
        "reminder_minutes": ("Λεπτά", "Minutes"),
        "reminder_hours": ("Ώρες", "Hours"),
        "reminder_days": ("Ημέρες", "Days"),
        "reminder_before": ("πριν", "before"),
        "reminder_success_toast": ("Η υπενθύμιση ορίστηκε επιτυχώς", "Reminder successfully set"),
        "reminders_initial_prompt_title": ("Ενεργοποίηση Υπενθυμίσεων", "Enable Reminders"),
        "reminders_initial_prompt_text": ("Το HelloMac μπορεί να σας στέλνει υπενθυμίσεις για να θυμάστε να πραγματοποιήσετε κλήσεις.", "HelloMac can send you reminders to make calls."),
        "reminders_permission_lost_title": ("Χάθηκε η πρόσβαση στις Υπενθυμίσεις", "Reminders Access Lost"),
        "reminders_permission_lost_text": ("Οι υπενθυμίσεις σταμάτησαν επειδή η άδεια πρόσβασης αφαιρέθηκε. Για να τις ενεργοποιήσετε ξανά, δώστε πρόσβαση από τις Ρυθμίσεις του macOS.", "Reminders have stopped because access permission was removed. To re-enable them, grant access from macOS Settings."),

        // --- ΠΑΡΑΘΥΡΟ ΥΠΕΝΘΥΜΙΣΕΩΝ ---
        "notifications_tooltip": ("Υπενθυμίσεις", "Reminders"),
        "notifications_window_title": ("Υπενθυμίσεις", "Reminders"),
        "notif_tab_new": ("Νέα", "New"),
        "notif_tab_upcoming": ("Επερχόμενες", "Upcoming"),
        "notif_tab_old": ("Παλιές", "Old"),
        "notif_new_pick_contact": ("Επιλέξτε επαφή για νέα υπενθύμιση:", "Pick a contact for a new reminder:"),
        "notif_new_search_placeholder": ("Αναζήτηση επαφής...", "Search contacts..."),
        "notif_new_start_btn": ("Συνέχεια...", "Continue..."),
        "notif_new_no_contact_selected": ("Δεν έχει επιλεγεί επαφή", "No contact selected"),
        "notif_new_change_contact": ("Αλλαγή", "Change"),
        "notif_no_upcoming": ("Δεν υπάρχουν επερχόμενες υπενθυμίσεις.", "No upcoming reminders."),
        "notif_no_upcoming_contact": ("Δεν υπάρχουν επερχόμενες υπενθυμίσεις για αυτή την επαφή.", "No upcoming reminders for this contact."),
        "notif_no_old": ("Δεν υπάρχουν παλιές υπενθυμίσεις.", "No old reminders."),
        "notif_no_old_contact": ("Δεν υπάρχουν παλιές υπενθυμίσεις για αυτή την επαφή.", "No old reminders for this contact."),
        "notif_copy_message": ("Αντιγραφή μηνύματος", "Copy message"),
        "notif_edit": ("Επεξεργασία", "Edit"),
        "notif_cancel_reminder": ("Ακύρωση υπενθύμισης", "Cancel reminder"),
        "notif_dismiss": ("Απόρριψη", "Dismiss"),
        "reminder_only_if_on_hint": ("Η υπενθύμιση θα εμφανιστεί μόνο αν ο υπολογιστής είναι ανοιχτός την ώρα εκείνη.", "The reminder will only appear if the computer is on at that time."),
        "notif_reminders_disabled_title": ("Ανενεργές Υπενθυμίσεις", "Reminders Are Off"),
        "notif_reminders_disabled_text": ("Ενεργοποιήστε τις υπενθυμίσεις κλήσεων από τις Ρυθμίσεις → Υπενθυμίσεις για να μπορείτε να δημιουργήσετε νέα.", "Turn on call reminders from Settings → Reminders to create a new one."),

        
        // --- UPDATER ---
        "update_available": ("Νέα Έκδοση Διαθέσιμη", "Update Available"),
        "update_text": ("Η έκδοση %@ είναι διαθέσιμη!\nΘέλετε να την εγκαταστήσετε τώρα;", "Version %@ is available!\nDo you want to install it now?"),
        "download": ("Εγκατάσταση & Επανεκκίνηση", "Install & Relaunch"),
        "up_to_date": ("Είστε Ενημερωμένοι", "Up to Date"),
        "up_to_date_text": ("Έχετε την πιο πρόσφατη έκδοση του HelloMac.", "You have the latest version of HelloMac."),
        "checking_for_updates": ("Έλεγχος για ενημερώσεις...", "Checking for updates..."),
        "up_to_date_thanks_text": ("Σας ευχαριστούμε θερμά που χρησιμοποιείτε το HelloMac!", "Thank you so much for using HelloMac!"),
        "update_error": ("Σφάλμα Ελέγχου", "Check Failed"),
        "update_error_text": ("Δεν ήταν δυνατός ο έλεγχος για νέες εκδόσεις. Ελέγξτε τη σύνδεσή σας στο διαδίκτυο.", "Could not check for updates. Please check your internet connection."),
        "downloading": ("Λήψη Ενημέρωσης...", "Downloading Update..."),
        "installing": ("Εγκατάσταση... Παρακαλώ περιμένετε.", "Installing... Please wait."),
        "download_error": ("Σφάλμα Λήψης", "Download Error"),
        "download_error_text": ("Υπήρξε πρόβλημα κατά τη λήψη της ενημέρωσης.", "There was a problem downloading the update."),
        
        // --- ΡΥΘΜΙΣΕΙΣ ---
        "settings_menu": ("Ρυθμίσεις...", "Settings..."),
        "settings_title": ("Ρυθμίσεις", "Settings"),
        "tab_updates": ("Ενημερώσεις", "Updates"),
        "settings_search_placeholder": ("Αναζήτηση", "Search"),
        "tab_appearance": ("Εμφάνιση", "Appearance"),
        "tab_buttons": ("Πλήκτρα", "Buttons"),
        "tab_speed_dial": ("Ταχεία Κλήση", "Speed Dial"),
        "tab_contacts_sync": ("Επαφές", "Contacts"),
        "tab_info": ("Πληροφορίες", "Info"),
        "app_tagline": ("Εφαρμογή κλήσεων", "Calling app"),
        "app_description": ("Πραγματοποίηση κλήσεων απευθείας από το Mac μέσω του iPhone.\n\nΜια ταχύτατη και ελαφριά εφαρμογή κλήσεων που μετατρέπει το Mac σας σε ένα πλήρες τηλεφωνικό κέντρο.\nΔιαθέτει άμεση πρόσβαση σε αγαπημένα, ιστορικό κλήσεων, πλήρη λίστα επαφών με αυτόματο συγχρονισμό από τις Επαφές του macOS και κλασικό πληκτρολόγιο με ταχεία κλήση.\nΕνσωματώνεται άψογα στο σύστημα, προσφέροντας κλήσεις από τη γραμμή μενού ή από οποιοδήποτε επιλεγμένο κείμενο, έξυπνες υπενθυμίσεις, λειτουργία απορρήτου, καθώς και εκτεταμένες επιλογές προσβασιμότητας και εμφάνισης.", "Make calls directly from your Mac via your iPhone.\n\nA blazing-fast and lightweight calling utility that turns your Mac into a complete telephony hub.\nIt features quick access to favorites, call history, a full contact list with automatic synchronization from macOS Contacts, and a classic keypad with speed dial.\nFlawlessly integrated into macOS, it offers one-click calls from the menu bar or any highlighted text, smart reminders, a dedicated privacy mode, and extensive accessibility and appearance options."),
        "app_website_label": ("Ιστοσελίδα εφαρμογής", "App Website"),
        "app_github_label": ("GitHub", "GitHub"),
        "app_shortcut_label": ("Συντόμευση: Ctrl + Option + Cmd + H", "Shortcut: Ctrl + Option + Cmd + H"),
        "current_version": ("Τρέχουσα έκδοση: %@", "Current version: %@"),
        "check_now": ("Έλεγχος τώρα", "Check Now"),
        "show_favorites_tab": ("Εμφάνιση μενού «Αγαπημένα»", "Show “Favorites” menu"),
        "show_contacts_tab": ("Εμφάνιση μενού «Επαφές»", "Show “Contacts” menu"),
        "show_keypad_tab": ("Εμφάνιση μενού «Πληκτρολόγιο»", "Show “Keypad” menu"),
        "show_history_tab": ("Εμφάνιση μενού «Ιστορικό»", "Show “History” menu"),
        "show_plus_tab": ("Εμφάνιση πλήκτρου «+»", "Show “+” button"),
        "play_app_keypad_sound": ("Ήχος πλήκτρων στο Πληκτρολόγιο", "Sound on keypad presses (App)"),
        "play_menu_bar_keypad_sound": ("Ήχος πλήκτρων στη Γραμμή Μενού", "Sound on keypad presses (Menu Bar)"),
        "show_contact_history_detail": ("Εμφάνιση ιστορικού στις λεπτομέρειες επαφής", "Show history in contact details"),
        "all_features_disabled": ("Όλες οι λειτουργίες είναι κρυφές.", "All features are hidden."),
        "enable_features_btn": ("Άνοιγμα Ρυθμίσεων", "Open Settings"),
        "enable_speed_dial": ("Ενεργοποίηση Ταχείας Κλήσης", "Enable Speed Dial"),

        "search_placeholder": ("Αναζήτηση...", "Search..."),
        "no_search_results": ("Δεν βρέθηκαν αποτελέσματα", "No results found"),
        "no_favorites_search": ("Δεν βρέθηκαν αποτελέσματα στα αγαπημένα\nΗ αναζήτηση της επαφής μπορεί να γίνει στις Επαφές", "No results found in favorites\nSearch for the contact in Contacts"),
        "search_visibility": ("Εμφάνιση αναζήτησης:", "Search Bar Visibility:"),
        "search_everywhere": ("Παντού", "Everywhere"),
        "search_favorites": ("Μόνο στα Αγαπημένα", "Only Favorites"),
        "search_contacts": ("Μόνο στις Επαφές", "Only Contacts"),
        "search_hidden": ("Πουθενά", "Nowhere"),
        "edit_contact": ("Επεξεργασία Επαφής", "Edit Contact"),
        "save_btn": ("Αποθήκευση", "Save"),
        "paste": ("Επικόλληση", "Paste"),
        "call_in_progress": ("Τερματίστε την τρέχουσα κλήση για να πραγματοποιήσετε μια νέα", "Please end the current call to start a new one"),
        "show_menu_bar_icon": ("Εμφάνιση εικονιδίου στη γραμμή μενού", "Show menu bar icon"),
        "theme_picker_label": ("Θέμα εφαρμογής", "App theme"),
        "theme_dark": ("Σκουρόχρωμη", "Dark"),
        "theme_light": ("Ανοιχτόχρωμη", "Light"),
        "theme_auto": ("Αυτόματο", "Auto"),
        "timezone_picker_label": ("Ζώνη ώρας", "Time zone"),
        "timezone_option_system": ("Ίδια με το macOS", "Same as macOS"),
        "timezone_option_custom": ("Προσαρμοσμένη", "Custom"),
        "timezone_custom_picker_label": ("Επιλογή ζώνης ώρας", "Select time zone"),
        "open_hellomac": ("Άνοιγμα HelloMac", "Open HelloMac"),

        // --- ΦΩΤΟΓΡΑΦΙΑ ΕΠΑΦΗΣ / DETAIL PANEL ---
        "choose_photo": ("Επιλογή φωτογραφίας", "Choose photo"),
        "remove_photo": ("Αφαίρεση φωτογραφίας", "Remove photo"),
        "contact_details": ("Στοιχεία Επαφής", "Contact Details"),
        "recent_calls": ("Πρόσφατες κλήσεις", "Recent calls"),
        "no_calls_yet": ("Δεν υπάρχουν κλήσεις ακόμα", "No calls yet"),
        "close_details": ("Κλείσιμο λεπτομερειών", "Close details"),
        "info_tooltip": ("Λεπτομέρειες", "Details"),

        // --- ΠΕΡΙΚΟΠΗ ΦΩΤΟΓΡΑΦΙΑΣ ---
        "crop_photo_title": ("Προσαρμογή Φωτογραφίας", "Adjust Photo"),
        "crop_photo_subtitle": ("Σύρετε για μετακίνηση, χρησιμοποιήστε το ρυθμιστικό για ζουμ", "Drag to reposition, use the slider to zoom"),
        "use_photo_btn": ("Χρήση Φωτογραφίας", "Use Photo"),
        "adjust_photo": ("Προσαρμογή / Ζουμ...", "Adjust / Zoom..."),

        // --- ΧΡΩΜΑ ΜΟΝΟΓΡΑΜΜΑΤΟΣ ---
        "monogram_color_swatch": ("Χρώμα μονογράμματος", "Monogram color"),
        "monogram_color_wheel": ("Περισσότερα χρώματα...", "More colors..."),

        // --- ΑΥΤΟΜΑΤΗ ΔΙΑΓΡΑΦΗ ΙΣΤΟΡΙΚΟΥ ---
        "history_autodelete_label": ("Αυτόματη διαγραφή ιστορικού:", "Auto-delete history:"),
        "history_autodelete_never": ("Ποτέ", "Never"),
        "history_autodelete_1_day": ("Μετά από 1 ημέρα", "After 1 day"),
        "history_autodelete_1_week": ("Μετά από 1 εβδομάδα", "After 1 week"),
        "history_autodelete_2_weeks": ("Μετά από 2 εβδομάδες", "After 2 weeks"),
        "history_autodelete_1_month": ("Μετά από 1 μήνα", "After 1 month"),
        "history_autodelete_3_months": ("Μετά από 3 μήνες", "After 3 months"),
        "history_autodelete_6_months": ("Μετά από 6 μήνες", "After 6 months"),
        "history_autodelete_1_year": ("Μετά από 1 χρόνο", "After 1 year"),
        
        "file_menu": ("Αρχείο", "File"),
        "import_contacts": ("Εισαγωγή επαφών...", "Import Contacts..."),
        "export_contacts": ("Εξαγωγή επαφών...", "Export Contacts..."),
        "import_export_title": ("Εισαγωγή & Εξαγωγή Επαφών (JSON)", "Import & Export Contacts (JSON)"),
        "export_success_title": ("Επιτυχία Εξαγωγής", "Export Successful"),
        "export_success_text": ("Οι επαφές εξήχθησαν επιτυχώς.", "Contacts were exported successfully."),
        "import_success_title": ("Επιτυχία Εισαγωγής", "Import Successful"),
        "import_success_text": ("Εισήχθησαν %d νέες επαφές (αγνοήθηκαν τα διπλότυπα).", "Imported %d new contacts (duplicates ignored)."),
        "import_error_title": ("Σφάλμα Εισαγωγής", "Import Error"),
        "import_error_text": ("Το αρχείο δεν είναι έγκυρο ή έχει καταστραφεί.", "The file is invalid or corrupted."),

        // --- CONTACTS FRAMEWORK SYNC (iCloud / iPhone μέσω Επαφών) ---
        "sync_with_contacts_app": ("Συγχρονισμός με Επαφές...", "Sync with Contacts..."),
        "contacts_sync_success_title": ("Ο συγχρονισμός ολοκληρώθηκε", "Sync Complete"),
        "contacts_sync_success_text": ("Προστέθηκαν %d νέες επαφές, ενημερώθηκαν %d υπάρχουσες.", "Added %d new contacts, updated %d existing."),
        "contacts_sync_error_title": ("Σφάλμα Συγχρονισμού", "Sync Error"),
        "contacts_sync_error_text": ("Δεν ήταν δυνατή η ανάγνωση των επαφών από το macOS.", "Could not read contacts from macOS."),
        "contacts_sync_not_authorized": ("Δεν δόθηκε άδεια πρόσβασης στις Επαφές.", "Access to Contacts was not authorized."),
        "contacts_sync_allow_btn": ("Επιτρέψτε Πρόσβαση", "Allow Access"),
        "contacts_sync_denied_title": ("Δεν υπάρχει πρόσβαση στις Επαφές", "No Access to Contacts"),
        "contacts_sync_denied_text": ("Η εφαρμογή HelloMac δεν διαθέτει άδεια πρόσβασης στις Επαφές. Η άδεια μπορεί να ενεργοποιηθεί από τις Ρυθμίσεις Απορρήτου του macOS.", "HelloMac does not have permission to access Contacts. Access can be enabled from macOS Privacy Settings."),
        "contacts_sync_open_settings_btn": ("Άνοιγμα Ρυθμίσεων", "Open Settings"),
        "contacts_sync_permission_lost_title": ("Χάθηκε η πρόσβαση στις Επαφές", "Contacts Access Lost"),
        "contacts_sync_permission_lost_text": ("Ο συγχρονισμός με τις Επαφές σταμάτησε επειδή η άδεια πρόσβασης αφαιρέθηκε. Για να τον ενεργοποιήσετε ξανά, δώστε πρόσβαση στις Επαφές από τις Ρυθμίσεις Απορρήτου του macOS.", "Contacts sync has stopped because access permission was removed. To re-enable it, grant access to Contacts from macOS Privacy Settings."),
        "contacts_sync_never": ("Ποτέ", "Never"),
        "contacts_sync_last_sync_label": ("Τελευταίος συγχρονισμός", "Last sync"),
        "contacts_sync_now_btn": ("Συγχρονισμός τώρα", "Sync Now"),
        "contacts_sync_settings_intro": ("Το HelloMac μπορεί μόνο να διαβάζει αυτόματα τις επαφές σας από την εφαρμογή Επαφές του macOS.\n\nΠροσοχή: Για τις επαφές που προέρχονται από αυτόν τον συγχρονισμό, τυχόν αλλαγή στο όνομα ή στο τηλέφωνο μέσα στο HelloMac δεν διατηρείται.\nΗ επαφή θα αντικατασταθεί στον επόμενο συγχρονισμό.", "HelloMac can only automatically read your contacts from the macOS Contacts app.\n\nNote: For contacts originating from this sync, any change to the name or phone number within HelloMac is not preserved.\nThe contact will be overwritten on the next sync."),
        "contacts_sync_enable_toggle": ("Ενεργοποίηση συγχρονισμού επαφών", "Enable Contacts sync"),
        "contacts_sync_auto_toggle": ("Αυτόματη ανανέωση στο παρασκήνιο", "Automatic background refresh"),
        "contacts_sync_auto_hint": ("Όταν είναι ενεργή, η εφαρμογή ελέγχει περιοδικά στο παρασκήνιο για αλλαγές στις Επαφές και ενημερώνει την λίστα επαφών σας αυτόματα.", "When active, the app periodically checks in the background for changes to Contacts and updates your contact list automatically."),
        "contacts_services_hint": ("Για να εμφανιστεί η επιλογή \"Κλήση με το HelloMac\" στο δεξί κλικ πάνω σε επιλεγμένο κείμενο, πρέπει να ενεργοποιηθεί μία φορά από τις Ρυθμίσεις Συστήματος (Πληκτρολόγιο → Συντομεύσεις πληκτρολογίου… → Υπηρεσίες → Κείμενο).", "To make \"Call with HelloMac\" appear when right-clicking selected text, it needs to be enabled once from System Settings (Keyboard → Keyboard Shortcuts… → Services → Text)."),
        "contacts_open_services_settings_btn": ("Άνοιγμα Ρυθμίσεων Υπηρεσιών…", "Open Services Settings…"),

        // --- ΕΝΗΜΕΡΩΣΗ ΓΙΑ ΣΥΓΧΡΟΝΙΣΜΟ ΕΠΑΦΩΝ (εμφανίζεται μία φορά, μετά από update ή στην πρώτη εκκίνηση) ---
        "contacts_sync_announce_title": ("Συγχρονισμός με Επαφές", "Contacts Sync"),
        "contacts_sync_announce_text": ("Η εφαρμογή HelloMac μπορεί μόνο να διαβάζει αυτόματα τις επαφές σας από την εφαρμογή Επαφές του macOS. Η ενεργοποίηση αυτής της δυνατότητας μπορεί να γίνει τώρα ή αργότερα από τις Ρυθμίσεις.\n\nΠροσοχή: Για τις επαφές που προέρχονται από αυτόν τον συγχρονισμό, τυχόν αλλαγή στο όνομα ή στο τηλέφωνο μέσα στο HelloMac δεν διατηρείται.\nΗ επαφή θα αντικατασταθεί στον επόμενο συγχρονισμό.", "The HelloMac app can only automatically read your contacts from the macOS Contacts app. This feature can be enabled now or later from Settings.\n\nNote: For contacts originating from this sync, any change to the name or phone number within HelloMac is not preserved.\nThe contact will be overwritten on the next sync."),

        // --- FACTORY RESET ---
        "factory_reset_title": ("Επαναφορά εργοστασιακών ρυθμίσεων", "Factory Reset"),
        "factory_reset_hint": ("Διαγράφει όλες τις επαφές, το ιστορικό κλήσεων, τις φωτογραφίες και όλες τις ρυθμίσεις. Η εφαρμογή επιστρέφει στην αρχική, άδεια κατάσταση.", "Deletes all contacts, call history, photos, and all settings. The app returns to its original, empty state."),
        "factory_reset_btn": ("Επαναφορά εργοστασιακών ρυθμίσεων...", "Factory Reset..."),
        "factory_reset_confirm1_title": ("Επιβεβαίωση συνέχειας", "Confirm to Continue"),
        "factory_reset_confirm1_text": ("Θα διαγραφούν όλες οι επαφές, το ιστορικό κλήσεων και όλες οι ρυθμίσεις της εφαρμογής.\nΗ ενέργεια αυτή δεν αναιρείται.", "All contacts, call history, and app settings will be deleted.\nThis action cannot be undone."),
        "factory_reset_confirm1_continue_btn": ("Συνέχεια", "Continue"),
        "factory_reset_confirm2_title": ("Τελική επιβεβαίωση", "Final Confirmation"),
        "factory_reset_confirm2_text": ("Η επιλογή \"Επαναφορά τώρα\" θα διαγράψει οριστικά όλα τα δεδομένα της εφαρμογής.", "Selecting \"Reset Now\" will permanently delete all app data."),
        "factory_reset_confirm2_wait_text": ("Αναμονή %d δευτερολέπτων...", "Waiting %d seconds..."),
        "factory_reset_confirm2_final_btn": ("Επαναφορά τώρα", "Reset Now"),
        "factory_reset_done_title": ("Η επαναφορά ολοκληρώθηκε", "Reset Complete"),
        "factory_reset_done_text": ("Όλα τα δεδομένα και οι ρυθμίσεις της εφαρμογής επαναφέρθηκαν στην αρχική τους κατάσταση.", "All app data and settings have been reset to their original state."),

        "select_folder": ("Επιλογή Φακέλου", "Select Folder"),
        "backup_title": ("Εισαγωγή & Εξαγωγή Επαφών με τις Φωτογραφίες τους (Φάκελος)", "Import & Export Contacts with their Photos (Folder)"),
        "import_backup": ("Επαναφορά Φακέλου...", "Restore Folder..."),
        "export_backup": ("Εξαγωγή Φακέλου...", "Export Folder..."),
        
        "tab_data": ("Δεδομένα", "Data"),
        "help_menu": ("Βοήθεια...", "Help..."),
        "backup_help_title": ("Βοήθεια Διαχείρισης Δεδομένων", "Data Management Help"),
        "backup_help_text": (
            "Εξαγωγή επαφών:\nΕξάγει τα ονόματα, τα τηλέφωνα και τα αγαπημένα σε ένα απλό αρχείο (.json).\n\nΕισαγωγή επαφών:\nΕισάγει ονόματα, τηλέφωνα και αγαπημένα από ένα απλό αρχείο (.json).\n\nΕξαγωγή Φακέλου:\nΕξάγει σε έναν φάκελο το αρχείο δεδομένων (.json) καθώς και όλες τις αποθηκευμένες φωτογραφίες επαφών.\n\nΕισαγωγή Φακέλου:\nΕισάγει από έναν φάκελο το αρχείο δεδομένων (.json) καθώς και όλες τις αποθηκευμένες φωτογραφίες επαφών.\n\n\nΚατά την εισαγωγή, η εφαρμογή προσθέτει τις νέες επαφές στη λίστα, αγνοώντας τυχόν διπλότυπα με βάση το τηλέφωνο.", 
            "Export Contacts:\nExports names, phone numbers, and favorites into a simple file (.json).\n\nImport Contacts:\nImports names, phone numbers, and favorites from a simple file (.json).\n\nExport Folder:\nExports to a folder the data file (.json) as well as all saved contact photos.\n\nImport Folder:\nImports from a folder the data file (.json) as well as all saved contact photos.\n\n\nDuring import, the app adds new contacts to the list, ignoring any duplicates based on phone number."
        ),
        "tab_search": ("Αναζήτηση", "Search"),
        "search_visibility_desc": ("Επιλέξτε πού θέλετε να εμφανίζεται η μπάρα αναζήτησης:", "Choose where the search bar should appear:"),
        "search_in_contacts": ("Στις Επαφές", "In Contacts"),
        "search_in_favorites": ("Στα Αγαπημένα", "In Favorites"),
        "search_in_history": ("Στο Ιστορικό", "In History"),
        "message_tooltip": ("Αποστολή μηνύματος", "Send message"),
        "show_messages_tab": ("Εμφάνιση πλήκτρου μηνυμάτων", "Show messages button"),

        // --- ΣΗΜΕΙΩΣΕΙΣ ΕΠΑΦΗΣ ---
        "notes_placeholder": ("Σημειώσεις (προαιρετικό)", "Notes (optional)"),
        "notes_title": ("Σημειώσεις", "Notes"),
        "show_contact_notes_in_detail": ("Εμφάνιση σημειώσεων στις λεπτομέρειες επαφής", "Show notes in contact details"),
        
        // --- ΛΕΙΤΟΥΡΓΙΑ ΑΠΟΡΡΗΤΟΥ (PRIVACY MODE) ---
        "privacy_mode_menu": ("Λειτουργία Απορρήτου", "Privacy Mode"),
        "privacy_mode_active_tooltip": ("Η λειτουργία απορρήτου είναι ενεργή — επιλογή για απενεργοποίηση", "Privacy mode is on — select to turn off"),
        "privacy_mode_disable_title": ("Απενεργοποίηση Απορρήτου", "Turn Off Privacy Mode"),
        "privacy_mode_disable_text": ("Η απενεργοποίηση θα κάνει ξανά ορατά παντού τα ονόματα, τα τηλέφωνα και τις φωτογραφίες των επαφών.", "Turning this off will make contact names, phone numbers, and photos visible again everywhere."),
        "privacy_mode_disable_btn": ("Απενεργοποίηση", "Turn Off"),
        "privacy_mode_blocked_title": ("Ενεργή Λειτουργία Απορρήτου", "Privacy Mode Is On"),
        "privacy_mode_blocked_text": ("Απαιτείται απενεργοποίηση της λειτουργίας απορρήτου για αυτή την ενέργεια.", "Privacy mode must be turned off to perform this action."),
        "privacy_mode_blocked_btn": ("Εντάξει", "OK"),
        "privacy_mode_search_disabled": ("Απαιτείται απενεργοποίηση της λειτουργίας απορρήτου\nγια την εμφάνιση αποτελεσμάτων αναζήτησης", "Turn off privacy mode to see search results"),
        "privacy_mode_enable_title": ("Ενεργοποίηση Απορρήτου", "Enable Privacy Mode"),
        "privacy_mode_enable_text": ("Η ενεργοποίηση θα κρύψει τα ονόματα, τα τηλέφωνα και τις φωτογραφίες των επαφών παντού στην εφαρμογή.", "Enabling this will hide contact names, phone numbers, and photos everywhere in the app."),
        "privacy_mode_enable_btn": ("Ενεργοποίηση", "Enable"),
        
        "show_menu_bar_plus_tab": ("Εμφάνιση πλήκτρου «+» (Γραμμή Μενού)", "Show “+” button (Menu Bar)"),

        // --- ΠΡΟΣΒΑΣΙΜΟΤΗΤΑ (ACCESSIBILITY) ---
        "tab_accessibility": ("Προσβασιμότητα", "Accessibility"),
        "accessibility_intro": ("Προσαρμόστε την εμφάνιση της εφαρμογής για ευκολότερη ανάγνωση και χρήση.", "Adjust how the app looks to make it easier to read and use."),
        "a11y_section_display": ("Οθόνη & Αντίθεση", "Display & Contrast"),
        "a11y_high_contrast": ("Υψηλή αντίθεση", "High contrast"),
        "a11y_high_contrast_desc": ("Ενισχύει τα περιγράμματα σε κουμπιά, διακόπτες και πεδία για καλύτερη διάκριση.", "Adds stronger borders to buttons, switches, and fields for better visibility."),
        "a11y_grayscale": ("Ασπρόμαυρη προβολή", "Grayscale"),
        "a11y_grayscale_desc": ("Αφαιρεί τον κορεσμό χρώματος από ολόκληρη τη διεπαφή.", "Removes color saturation from the entire interface."),
        "a11y_section_text": ("Κείμενο", "Text"),
        "a11y_increase_text_size": ("Μεγέθυνση κειμένου", "Larger text"),
        "a11y_increase_text_size_desc": ("Αυξάνει το μέγεθος του κειμένου σε όλη την εφαρμογή.", "Increases text size throughout the app."),
        "a11y_bold_text": ("Έντονα γράμματα", "Bold text"),
        "a11y_bold_text_desc": ("Εμφανίζει το κείμενο πιο έντονο για καλύτερη αναγνωσιμότητα.", "Displays text more boldly for improved readability."),
        "a11y_section_interface": ("Διεπαφή", "Interface"),
        "a11y_ui_scale": ("Μεγέθυνση διεπαφής", "Interface zoom"),
        "a11y_ui_scale_desc": ("Μεγεθύνει ολόκληρη τη διεπαφή της εφαρμογής.", "Zooms in the entire app interface."),
        "a11y_ui_scale_label": ("Επίπεδο μεγέθυνσης:", "Zoom level:"),
        "a11y_larger_hit_targets": ("Μεγαλύτερες περιοχές πατήματος", "Larger tap targets"),
        "a11y_larger_hit_targets_desc": ("Μεγεθύνει όσα κουμπιά και πλήκτρα είναι μικρά για ευκολότερο πάτημα.", "Enlarges any buttons and keys that are small for easier pressing."),
        "a11y_reset_btn": ("Επαναφορά όλων στις προεπιλογές", "Reset all to defaults"),
        "a11y_restart_hint": ("", ""),
        "percent_100": ("100%", "100%"),
        "percent_110": ("110%", "110%"),
        "percent_120": ("120%", "120%"),
        "percent_130": ("130%", "130%"),
        "text_size_off": ("Κανονικό", "Off"),
        "text_size_step2": ("Μεγαλύτερο", "Larger"),
        "text_size_step3": ("Πολύ μεγαλύτερο", "Much larger"),
        "text_size_largest": ("Πολύ μεγάλο", "Largest"),

        // --- ΟΜΑΔΕΣ ΕΠΑΦΩΝ ---
        "tab_groups": ("Ομάδες", "Groups"),
        "groups_enable_toggle": ("Ενεργοποίηση ομάδων επαφών", "Enable contact groups"),
        "groups_enable_desc": ("Οργανώστε τις επαφές σας σε προσαρμοσμένες ομάδες, όπως «Εργασία» ή «Οικογένεια».", "Organize your contacts into custom groups, like “Work” or “Family”."),
        "groups_manage_title": ("Οι ομάδες μου", "My groups"),
        "groups_add_placeholder": ("Νέα ομάδα...", "New group..."),
        "groups_add_btn": ("Προσθήκη", "Add"),
        "groups_empty": ("Δεν έχετε δημιουργήσει ομάδες ακόμα.", "You haven't created any groups yet."),
        "groups_rename_tooltip": ("Μετονομασία", "Rename"),
        "groups_delete_tooltip": ("Διαγραφή ομάδας", "Delete group"),
        "groups_delete_confirm_title": ("Διαγραφή ομάδας «%@»;", "Delete group “%@”?"),
        "groups_delete_confirm_text": ("Η ομάδα θα αφαιρεθεί από όλες τις επαφές που ανήκουν σε αυτή. Οι ίδιες οι επαφές δεν θα διαγραφούν.", "This group will be removed from every contact in it. The contacts themselves will not be deleted."),
        "groups_delete_confirm_btn": ("Διαγραφή", "Delete"),
        "groups_duplicate_name": ("Υπάρχει ήδη ομάδα με αυτό το όνομα", "A group with this name already exists"),
        "groups_char_limit_hint": ("Έως 20 χαρακτήρες", "Up to 20 characters"),
        "groups_rename_prompt_title": ("Μετονομασία ομάδας", "Rename group"),
        "groups_field_label": ("Ομάδες", "Groups"),
        "groups_none_selected": ("Καμία ομάδα", "No group"),
        "groups_select_menu_title": ("Επιλογή ομάδων", "Select groups"),
        "groups_filter_all": ("Όλες οι επαφές", "All contacts"),
        "groups_detail_badge_tooltip": ("Προβολή επαφών της ομάδας", "View contacts in this group"),
        "groups_detail_popover_title": ("Επαφές στην ομάδα «%@»", "Contacts in “%@”"),
        "groups_detail_popover_empty": ("Δεν υπάρχουν άλλες επαφές σε αυτή την ομάδα.", "No other contacts in this group."),
        "groups_no_group_assigned": ("Χωρίς ομάδα", "No group"),
        "groups_filter_tooltip": ("Φίλτρο ομάδας", "Group filter"),
        "search_in_group_placeholder": ("Αναζήτηση στην ομάδα «%@»...", "Search in “%@”..."),
        "search_in_selected_groups": ("Αναζήτηση στις επιλεγμένες ομάδες...", "Search in selected groups..."),
        "groups_new_group_menu_item": ("Νέα ομάδα...", "New group..."),
        "speed_dial_active_tooltip": ("Ταχεία Κλήση ενεργή", "Speed Dial active"),
        "speed_dial_manage_menu_item": ("Διαχείριση Ταχείας Κλήσης...", "Manage Speed Dial..."),
        "speed_dial_empty": ("Δεν έχουν οριστεί αριθμοί ταχείας κλήσης.", "No speed dial numbers set."),
        "groups_add_prompt_title": ("Νέα ομάδα", "New group"),

        // --- ΣΥΣΤΗΜΑ / ΜΕΝΟΥ ΕΠΕΞΕΡΓΑΣΙΑΣ (EDIT MENU) ---
        "edit_menu": ("Επεξεργασία", "Edit"),
        "cut": ("Αποκοπή", "Cut"),
        "copy": ("Αντιγραφή", "Copy"),
        "select_all": ("Επιλογή όλων", "Select All"),
        "start_dictation": ("Έναρξη υπαγόρευσης...", "Start Dictation..."),
        "emoji_and_symbols": ("Emoji και σύμβολα", "Emoji & Symbols"),
        "search_with_google": ("Αναζήτηση με το Google", "Search with Google"),
        "share_menu": ("Κοινοποίηση...", "Share..."),

        // --- ΜΠΑΡΑ ΜΕΝΟΥ (MENU BAR) ---
        "menubar_call_copied": ("Κλήση στο αντιγραμμένο: %@", "Call copied: %@"),
        "menubar_more_favorites": ("Περισσότερα αγαπημένα...", "More favorites..."),
        "menubar_more_results": ("Περισσότερα αποτελέσματα...", "More results..."),
        "menubar_more_history": ("Περισσότερο ιστορικό...", "More history..."),
        "menubar_number_placeholder": ("Αριθμός...", "Number..."),
        "menubar_keypad_a11y": ("Πλήκτρα", "Keypad"),
        "menubar_close_keypad_a11y": ("Κλείσιμο Πλήκτρων", "Close Keypad"),

        // --- ΥΠΕΝΘΥΜΙΣΕΙΣ: ΕΠΙΠΛΕΟΝ ΜΗΝΥΜΑΤΑ ---
        "reminders_clear_upcoming_title": ("Καθαρισμός επερχόμενων;", "Clear upcoming?"),
        "reminders_clear_old_title": ("Καθαρισμός παλιών;", "Clear old?"),
        "reminders_clear_upcoming_text": ("Όλες οι επερχόμενες υπενθυμίσεις θα ακυρωθούν και θα διαγραφούν οριστικά.", "All upcoming reminders will be canceled and permanently deleted."),
        "reminders_clear_old_text": ("Το ιστορικό υπενθυμίσεων θα διαγραφεί οριστικά.", "Reminder history will be permanently deleted."),
        "reminder_at_event_time": ("τη στιγμή του συμβάντος", "at event time"),
        "reminder_days_value": ("%@ ημέρ%@", "%@ day%@"),
        "reminder_hours_value": ("%@ ώρ%@", "%@ hour%@"),
        "reminder_minutes_value": ("%@ λεπτά", "%@ minutes"),
        "reminder_invalid_time_title": ("Μη έγκυρη ώρα", "Invalid time"),
        "reminder_invalid_time_text": ("Η ημερομηνία και ώρα της ειδοποίησης δεν μπορεί να είναι στο παρελθόν.", "The reminder date and time cannot be in the past."),
        "reminder_some_dont_fit_title": ("Ορισμένες υπενθυμίσεις δεν χωράνε", "Some reminders don't fit"),
        "reminder_continue_btn": ("Συνέχεια", "Continue"),

        // --- ΡΥΘΜΙΣΕΙΣ (ΠΡΟΣΘΕΤΑ) ---
        "settings_speeddial_intro": ("Αντιστοιχίστε αριθμούς στα πλήκτρα 1-9 για γρήγορη κλήση από το πληκτρολόγιο της εφαρμογής.", "Assign numbers to keys 1-9 for quick dialing from the app's keypad."),
        "settings_view_on_github": ("Προβολή στο GitHub", "View on GitHub"),
        "settings_loading_release_notes": ("Φόρτωση δεδομένων από GitHub...", "Loading release notes..."),
        "settings_whats_new": ("Τι νέο υπάρχει", "What's New"),
        "settings_release_notes_load_error": ("Δεν ήταν δυνατή η φόρτωση των σημειώσεων έκδοσης.\nΕλέγξτε τη σύνδεσή σας στο διαδίκτυο.", "Could not load release notes.\nPlease check your internet connection."),

        // --- ΥΠΕΝΘΥΜΙΣΕΙΣ: ΚΑΤΑΛΟΙΠΑ ---
        "reminder_unreachable_text": ("Το συμβάν είναι πολύ κοντά ώστε να προλάβουν να χτυπήσουν: %@. Θα οριστούν μόνο οι υπόλοιπες υπενθυμίσεις.", "The event is too soon for these to fire: %@. Only the remaining reminders will be set."),
        "reminder_ordinal_label": ("%@%@ Υπενθύμιση:", "%@%@ Reminder:"),
    ]
    
    guard let translation = strings[key] else { return key }
    let text = isGreek ? translation.el : translation.en
    return arg.isEmpty ? text : String(format: text, arg)
}

func L2(_ key: String, _ arg1: String, _ arg2: String) -> String {
    return String(format: L(key), arg1, arg2)
}